# Generated by Django 3.2.7 on 2022-04-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rate_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='content',
            field=models.IntegerField(choices=[(1, '1 '), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5 '), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 t'), (10, '10 ')], default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='design',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 '), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5 '), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')], default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usability',
            field=models.IntegerField(choices=[(1, '1 '), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5 '), (6, '6 '), (7, '7 '), (8, '8 '), (9, '9 '), (10, '10 ')], default=0),
        ),
    ]
